#!/bin/bash
echo $DOCKER_HUB_PASSWORD | docker login -u=$DOCKER_HUB_USERNAME $DOCKER_HUB_PATH --password-stdin
# docker build -t $DOCKER_HUB_PATH/$DOCKER_HUB_NAMESPACE/${DOCKER_HUB_REPOSITORY}_${LINUX_ARM32V7_IMAGE_NAME}:$TRAVIS_TAG -f docker/Dockerfile.${LINUX_ARM32V7_IMAGE_NAME} .
docker build -t $DOCKER_HUB_PATH/$DOCKER_HUB_NAMESPACE/${DOCKER_HUB_REPOSITORY}:$TRAVIS_TAG -f docker/Dockerfile .
docker image ls
# docker push $DOCKER_HUB_PATH/$DOCKER_HUB_NAMESPACE/${DOCKER_HUB_REPOSITORY}_${LINUX_ARM32V7_IMAGE_NAME}:$TRAVIS_TAG
docker push $DOCKER_HUB_PATH/$DOCKER_HUB_NAMESPACE/${DOCKER_HUB_REPOSITORY}:$TRAVIS_TAG
